# Generated by Django 5.0.6 on 2024-07-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('click', 'Click'), ('swipe', 'Swipe')], max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bots.bot')),
            ],
        ),
    ]
