# Generated by Django 5.0.6 on 2024-07-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_owner_alter_bot_description_botaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='emulator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
